# Generated by Django 4.2.7 on 2023-12-10 15:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('iso2', models.CharField(max_length=2)),
                ('continent', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('name', 'iso2')},
            },
        ),
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=2000)),
                ('answer', models.CharField(max_length=250)),
                ('image_url', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=250)),
                ('difficulty', models.IntegerField()),
                ('question_type', models.CharField(max_length=250)),
                ('notes', models.CharField(max_length=250)),
                ('google_streetview_url', models.CharField(max_length=250)),
                ('airtable_id', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.country')),
            ],
        ),
    ]
