# Generated by Django 4.2.7 on 2023-12-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_facts_fact_alter_country_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='country',
        ),
        migrations.AddField(
            model_name='fact',
            name='countries',
            field=models.ManyToManyField(related_name='facts', to='quiz.country'),
        ),
    ]
