# Generated by Django 4.2.7 on 2023-12-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_fact_country_fact_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='category',
            field=models.CharField(choices=[('coverage', 'Coverage'), ('driving_direction', 'Driving direction'), ('google_car', 'Google Car'), ('language', 'Language'), ('license_plate', 'License Plate'), ('road_lines', 'Road Lines'), ('settlement_sign', 'Settlement Sign'), ('bollards', 'Bollards'), ('street_numbering', 'Street Numbering'), ('street_markings', 'Street Markings'), ('street_name', 'Street Name'), ('street_sign', 'Street Sign'), ('poles', 'Poles'), ('other', 'Other'), ('cars', 'Cars'), ('pedestrian_crossign_sign', 'Pedestrian Crossign Sign'), ('buildings', 'Buildings'), ('flora', 'Flora')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fact',
            name='notes',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='fact',
            name='question_type',
            field=models.CharField(choices=[('SingleCountry', 'SingleCountry'), ('SingleContinent', 'SingleContinent'), ('MultipleCountry', 'MultipleCountry'), ('MultipleContinent', 'MultipleContinent'), ('NoAnswer', 'NoAnswer')], max_length=100),
        ),
    ]
