# Generated by Django 4.2.7 on 2023-12-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_fact_category_alter_fact_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='google_streetview_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fact',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
