# Generated by Django 4.2.7 on 2023-12-10 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_fact_google_streetview_url_alter_fact_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='question',
        ),
    ]
