# Generated by Django 4.2.7 on 2023-12-12 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_fact_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(blank=True, choices=[('coverage', 'Coverage'), ('driving_direction', 'Driving direction'), ('google_car', 'Google Car'), ('language', 'Language'), ('license_plate', 'License Plate'), ('road_lines', 'Road Lines'), ('settlement_sign', 'Settlement Sign'), ('bollards', 'Bollards'), ('street_numbering', 'Street Numbering'), ('street_markings', 'Street Markings'), ('street_name', 'Street Name'), ('street_sign', 'Street Sign'), ('poles', 'Poles'), ('other', 'Other'), ('cars', 'Cars'), ('pedestrian_crossign_sign', 'Pedestrian Crossign Sign'), ('buildings', 'Buildings'), ('flora', 'Flora')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('countries', models.ManyToManyField(blank=True, null=True, related_name='quizzes', to='quiz.country')),
            ],
        ),
    ]
