# Generated by Django 4.2.7 on 2023-12-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('name',)},
        ),
    ]
