# Generated by Django 4.2.7 on 2023-12-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_quiz_options_alter_quiz_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='quizzes', to='quiz.country'),
        ),
    ]
