# Generated by Django 4.2.7 on 2023-12-14 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0010_alter_fact_answer_alter_fact_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('in_progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='in_progress', max_length=100)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quiz Sessions',
                'unique_together': {('user', 'state')},
            },
        ),
        migrations.CreateModel(
            name='QuizSessionFact',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_seen_answer', models.BooleanField(default=False)),
                ('review_result', models.CharField(blank=True, choices=[('correct', 'Correct'), ('false', 'False')], max_length=100, null=True)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.fact')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('quiz_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quiz Sessions',
                'unique_together': {('quiz_session', 'fact')},
            },
        ),
    ]
