# Generated by Django 4.2.7 on 2023-12-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_quizsession_quizsessionfact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsessionfact',
            name='has_seen_answer',
        ),
        migrations.AddField(
            model_name='quizsessionfact',
            name='sort_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
