# Generated by Django 4.2.7 on 2023-12-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_remove_quizsessionfact_has_seen_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizsessionfact',
            options={'verbose_name_plural': 'Quiz Session Facts'},
        ),
        migrations.AlterField(
            model_name='quizsessionfact',
            name='review_result',
            field=models.CharField(blank=True, choices=[('correct', 'Correct'), ('false', 'False'), ('not_set', 'Not Set')], max_length=100, null=True),
        ),
    ]
