# Generated by Django 4.2.7 on 2023-12-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_quizsessionfact_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizsession',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='quizsession',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'in_progress')), fields=('user', 'state'), name='unique_user_in_progress'),
        ),
    ]
