# Generated by Django 4.2.7 on 2023-12-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_quizsession_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
