# Generated by Django 4.2.7 on 2023-12-15 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_country_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='num_facts',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizsessionfact',
            name='quiz_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizsessionfacts', to='quiz.quizsession'),
        ),
    ]
