# Generated by Django 4.2.7 on 2023-12-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_quiz_num_facts_alter_quizsessionfact_quiz_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='category',
            field=models.CharField(choices=[('coverage', 'Coverage'), ('driving_direction', 'Driving direction'), ('google_car', 'Google Car'), ('language', 'Language'), ('license_plate', 'License Plate'), ('road_lines', 'Road Lines'), ('settlement_sign', 'Settlement Sign'), ('bollards', 'Bollards'), ('street_numbering', 'Street Numbering'), ('street_markings', 'Street Markings'), ('street_name', 'Street Name'), ('street_sign', 'Street Sign'), ('poles', 'Poles'), ('other', 'Other'), ('cars', 'Cars'), ('pedestrian_crossign_sign', 'Pedestrian Crossing Sign'), ('buildings', 'Buildings'), ('flora', 'Flora')], max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(blank=True, choices=[('coverage', 'Coverage'), ('driving_direction', 'Driving direction'), ('google_car', 'Google Car'), ('language', 'Language'), ('license_plate', 'License Plate'), ('road_lines', 'Road Lines'), ('settlement_sign', 'Settlement Sign'), ('bollards', 'Bollards'), ('street_numbering', 'Street Numbering'), ('street_markings', 'Street Markings'), ('street_name', 'Street Name'), ('street_sign', 'Street Sign'), ('poles', 'Poles'), ('other', 'Other'), ('cars', 'Cars'), ('pedestrian_crossign_sign', 'Pedestrian Crossing Sign'), ('buildings', 'Buildings'), ('flora', 'Flora')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='num_facts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
