# Generated by Django 4.2.7 on 2023-12-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_alter_fact_category_alter_quiz_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.CharField(default='pending', max_length=250),
            preserve_default=False,
        ),
    ]
