# Generated by Django 4.2.7 on 2023-12-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_country_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='region_slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
