# Generated by Django 4.2.7 on 2023-12-17 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_remove_fact_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='quiz.category'),
        ),
    ]
