# Generated by Django 4.2.7 on 2023-12-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_fact_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
    ]
