# Generated by Django 4.2.7 on 2023-12-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_region_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='question_type',
        ),
    ]
