# Generated by Django 4.2.7 on 2023-12-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_remove_fact_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='distinctive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fact',
            name='distinctive_in_region',
            field=models.BooleanField(default=False),
        ),
    ]
