# Generated by Django 4.2.7 on 2023-12-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_fact_distinctive_fact_distinctive_in_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='distinctive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fact',
            name='distinctive_in_region',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
