# Generated by Django 4.2.7 on 2023-12-21 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_alter_fact_distinctive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='quiz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_quiz', to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='region',
            name='quiz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_quiz', to='quiz.quiz'),
        ),
    ]
