# Generated by Django 4.2.7 on 2023-12-21 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_category_quiz_region_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='quiz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_quiz', to='quiz.quiz'),
        ),
    ]
