# Generated by Django 4.2.7 on 2023-12-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_country_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='difficulty',
        ),
    ]
