# Generated by Django 4.2.7 on 2023-12-23 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0034_remove_fact_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFactPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_count', models.IntegerField(default=0)),
                ('box', models.IntegerField(default=0)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.fact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Fact Performances',
                'unique_together': {('user', 'fact')},
            },
        ),
    ]
