# Generated by Django 4.2.7 on 2023-12-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0036_alter_quizsession_user_alter_quizsessionfact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfactperformance',
            name='box',
            field=models.IntegerField(default=1),
        ),
    ]
