# Generated by Django 4.2.7 on 2023-12-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0037_alter_userfactperformance_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='right_hand_traffic',
            field=models.BooleanField(default=True),
        ),
    ]
