# Generated by Django 4.2.7 on 2023-12-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_country_right_hand_traffic'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
