# Generated by Django 4.2.7 on 2024-01-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0040_remove_fact_countries_fact_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='google_streetview_latlng',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
