# Generated by Django 4.2.7 on 2024-02-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0041_fact_google_streetview_latlng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='distinctive',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='distinctive_in_region',
        ),
    ]
