# Generated by Django 4.2.7 on 2024-02-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0042_remove_fact_distinctive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='image_is_landscape',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
